### ISSUE TITLE
I want to get the result of making my face in 3D.

### ISSUE THREAD

**Issue by KScript92** [nabeel3133/3D-texture-fitting#1]
Hello. Your code is really simple and cool. I want to get an input image using my face. Can you tell me what to do?

**Comment by nabeel3133** [comment]
Hello. Thank you for checking out my repository. Please refer to the following link (https://github.com/cleardusk/3DDFA) for generating your own 3D Face and then using this texture fitting repository in order to have a better texture of your face.
