### ISSUE TITLE
The problem of downloading BFM model

### ISSUE THREAD

**Issue by csyuhao** [nabeel3133/3D-texture-fitting#3]
Hi @nabeel3133, thanks for you awesome work.

I have a problem of downloading BFM model. In readme of this repo, you write
```
After you have acquired BFM, extract the BaselFaceModel.tgz and go toPublicMM1 folder, copy 01_MorphableModel.mat, BFM_exp_idx.mat and paste it in ./3D-texture-fitting/configs folder.
```

However, I can not find `BFM_exp_idx.mat` in `BaselFaceModel.tgz`, whose file tree is as follows:
```
PublicMM1
    │  01_MorphableModel.mat
    │  04_attributes.mat
    │  
    ├─09_mask
    │      face05_4seg.mat
    │      face05_4seg.txt
    │      
    ├─11_feature_points
    │      Farkas_face05.fp
    │      fit_face05_9.fp
    │      MPEG4_FDP_face05.fp
    │      
    ├─13_symmetry_indices
    │      face05_symlist.txt
    │      
    └─matlab
            apply_attributes.m
            coef2object.m
            defrp.m
            display_face.m
            idx2intl.m
            load_model.m
            object2coef.m
            plywrite.m
            script_gen_random_head.m
            script_load_scan.m
            script_render_fittings.m
```

Can you give me advice?

**Comment by annietranscr** [comment]
Hello 


> Hi @nabeel3133, thanks for you awesome work.
> 
> I have a problem of downloading BFM model. In readme of this repo, you write
> 
> ```
> After you have acquired BFM, extract the BaselFaceModel.tgz and go toPublicMM1 folder, copy 01_MorphableModel.mat, BFM_exp_idx.mat and paste it in ./3D-texture-fitting/configs folder.
> ```
> 
> However, I can not find `BFM_exp_idx.mat` in `BaselFaceModel.tgz`, whose file tree is as follows:
> 
> ```
> PublicMM1
>     │  01_MorphableModel.mat
>     │  04_attributes.mat
>     │  
>     ├─09_mask
>     │      face05_4seg.mat
>     │      face05_4seg.txt
>     │      
>     ├─11_feature_points
>     │      Farkas_face05.fp
>     │      fit_face05_9.fp
>     │      MPEG4_FDP_face05.fp
>     │      
>     ├─13_symmetry_indices
>     │      face05_symlist.txt
>     │      
>     └─matlab
>             apply_attributes.m
>             coef2object.m
>             defrp.m
>             display_face.m
>             idx2intl.m
>             load_model.m
>             object2coef.m
>             plywrite.m
>             script_gen_random_head.m
>             script_load_scan.m
>             script_render_fittings.m
> ```
> 
> Can you give me advice?

Thank you very much for checking out the repository and filing an issue.
Kindly download the file **BFM_exp_idx.mat**  from [https://drive.google.com/file/d/1kv0sJZRBADOC2dOZMrXhd6k_kJB8Frc4/view?usp=sharing](url)

**Comment by nabeel3133** [comment]
> Hi @nabeel3133, thanks for you awesome work.
> 
> I have a problem of downloading BFM model. In readme of this repo, you write
> 
> ```
> After you have acquired BFM, extract the BaselFaceModel.tgz and go toPublicMM1 folder, copy 01_MorphableModel.mat, BFM_exp_idx.mat and paste it in ./3D-texture-fitting/configs folder.
> ```
> 
> However, I can not find `BFM_exp_idx.mat` in `BaselFaceModel.tgz`, whose file tree is as follows:
> 
> ```
> PublicMM1
>     │  01_MorphableModel.mat
>     │  04_attributes.mat
>     │  
>     ├─09_mask
>     │      face05_4seg.mat
>     │      face05_4seg.txt
>     │      
>     ├─11_feature_points
>     │      Farkas_face05.fp
>     │      fit_face05_9.fp
>     │      MPEG4_FDP_face05.fp
>     │      
>     ├─13_symmetry_indices
>     │      face05_symlist.txt
>     │      
>     └─matlab
>             apply_attributes.m
>             coef2object.m
>             defrp.m
>             display_face.m
>             idx2intl.m
>             load_model.m
>             object2coef.m
>             plywrite.m
>             script_gen_random_head.m
>             script_load_scan.m
>             script_render_fittings.m
> ```
> 
> Can you give me advice?

Thank you very much for checking out the repository and filing an issue.
Kindly download the file **BFM_exp_idx.mat** from [https://drive.google.com/file/d/1kv0sJZRBADOC2dOZMrXhd6k_kJB8Frc4/view?usp=sharing](url)

**Comment by csyuhao** [comment]
Sorry, I can not access the link. The Google Drive tell me I need access.
![批注 2020-07-07 091307](https://user-images.githubusercontent.com/24415219/86681406-20d5c600-c032-11ea-9019-73cafd76c13d.png)
